Repository AY2324S2-CS2103T-T09-1/tp, pull requests merged in 2024-04, with the labels that each got.

#114 Branch fix weak command
  src/main/java/seedu/teachstack/logic/parser/SetWeakThresholdCommandParser.java
  src/main/java/seedu/teachstack/model/Model.java
  src/main/java/seedu/teachstack/model/ModelManager.java
  src/test/java/seedu/teachstack/logic/parser/SetWeakThresholdCommandParserTest.java
Labels: bug

#113 Random feature
  src/main/java/seedu/teachstack/logic/commands/RandomCommand.java
  src/main/java/seedu/teachstack/logic/parser/AddressBookParser.java
  src/main/java/seedu/teachstack/logic/parser/RandomCommandParser.java
  src/main/java/seedu/teachstack/model/Model.java
  src/main/java/seedu/teachstack/model/ModelManager.java
  src/main/java/seedu/teachstack/model/group/Group.java
  src/main/java/seedu/teachstack/model/person/Grade.java
  src/test/java/seedu/teachstack/logic/commands/AddCommandTest.java
  src/test/java/seedu/teachstack/logic/commands/RandomCommandTest.java
  src/test/java/seedu/teachstack/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/teachstack/logic/parser/ParserUtilTest.java
  src/test/java/seedu/teachstack/logic/parser/RandomCommandParserTest.java
  src/test/java/seedu/teachstack/model/ModelManagerTest.java
  src/test/java/seedu/teachstack/testutil/PersonUtil.java
Labels: type.Task, priority.Medium

#123 UG tableofcontents
  docs/UserGuide.md
Labels: documentation

#125 Add sections 2, 2.1, 6.1, 7.3 and 7.14 to UserGuide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/setTheme.png
  docs/images/understandingUi.png
  docs/index.md
Labels: documentation

#116 Branch statistics
  src/main/java/seedu/teachstack/logic/commands/CommandResult.java
  src/main/java/seedu/teachstack/logic/commands/SummaryCommand.java
  src/main/java/seedu/teachstack/logic/parser/AddressBookParser.java
  src/main/java/seedu/teachstack/model/AddressBook.java
  src/main/java/seedu/teachstack/model/Model.java
  src/main/java/seedu/teachstack/model/person/Grade.java
  src/main/java/seedu/teachstack/model/person/UniquePersonList.java
  src/main/java/seedu/teachstack/ui/MainWindow.java
  src/test/java/seedu/teachstack/logic/commands/CommandResultTest.java
  src/test/java/seedu/teachstack/logic/commands/SummaryCommandTest.java
  src/test/java/seedu/teachstack/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.Medium

#128 Update UG to include find command
  docs/UserGuide.md
Labels: documentation

#129 Update the user guide
  docs/UserGuide.md
  docs/images/AddUI.png
  docs/images/ArchiveUI.png
  docs/images/DeleteArchivedUI.png
  docs/images/EditArchivedUI.png
  docs/images/UnarchivedUI.png
  docs/images/helpMessage.png
Labels: documentation

#130 Update UG features
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/setWeakAfter.png
  docs/images/setWeakBefore.png
  docs/images/summary.png
Labels: documentation

#131 Fix adding or editing person with student id or email that exists in list
  src/main/java/seedu/teachstack/logic/commands/EditCommand.java
  src/main/java/seedu/teachstack/model/AddressBook.java
  src/main/java/seedu/teachstack/model/Model.java
  src/main/java/seedu/teachstack/model/ModelManager.java
  src/main/java/seedu/teachstack/model/person/Grade.java
  src/main/java/seedu/teachstack/model/person/Person.java
  src/main/java/seedu/teachstack/model/person/UniquePersonList.java
  src/test/java/seedu/teachstack/logic/commands/AddCommandTest.java
  src/test/java/seedu/teachstack/logic/commands/EditCommandTest.java
  src/test/java/seedu/teachstack/model/ModelManagerTest.java
  src/test/java/seedu/teachstack/model/person/PersonTest.java
  src/test/java/seedu/teachstack/model/person/UniquePersonListTest.java
Labels: bug

#134 Update case-sensitivity
  docs/UserGuide.md
  docs/images/DeleteUI.png
  docs/images/editUI.png
Labels: documentation

#136 Rename EditUI.png
  docs/UserGuide.md
  docs/images/EditUI.png
Labels: bug

#199 Update UG to fix some documentation bugs
  docs/UserGuide.md
Labels: bug, documentation

#200 Fix duplicate person in person list and archived list
  src/main/java/seedu/teachstack/logic/commands/AddCommand.java
  src/main/java/seedu/teachstack/logic/commands/EditCommand.java
  src/test/java/seedu/teachstack/logic/commands/AddCommandTest.java
Labels: bug, priority.High

#209 Fix unnessary arrow with 0 students
  src/main/java/seedu/teachstack/logic/commands/SummaryCommand.java
Labels: bug

#208 Fix duplicate person in persons list and archived list
  src/main/java/seedu/teachstack/logic/commands/AddCommand.java
  src/main/java/seedu/teachstack/logic/commands/EditArchiveCommand.java
  src/main/java/seedu/teachstack/logic/commands/EditCommand.java
Labels: bug, priority.High

#205 Fix UG bugs
  docs/UserGuide.md
Labels: bug, documentation

#211 Add implementation details of random feature to DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/RandomActivityDiagram.puml
  docs/diagrams/RandomSequenceDiagram.puml
  docs/diagrams/RandomState1.puml
  docs/diagrams/RandomState2.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/RandomActivityDiagram.png
  docs/images/RandomSequenceDiagram.png
  docs/images/RandomState1.png
  docs/images/RandomState2.png
Labels: documentation

#210 Dg Update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SetWeakSequenceDiagram.puml
  docs/images/SetWeakSequenceDiagram.png
  docs/images/weak_label.png
Labels: documentation

#212 Fix RandomState2
  docs/diagrams/RandomState2.puml
  docs/images/RandomState2.png
Labels: bug, documentation

#223 Update glossary section
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#222 Add acknowledgements to DG
  docs/DeveloperGuide.md
Labels: documentation

#227 Add instructions for manual testing
  docs/DeveloperGuide.md
Labels: documentation

#225 Ug Updates
  docs/UserGuide.md
  docs/images/teachstack.png
Labels: documentation

#226 Add planned enhancements
  docs/DeveloperGuide.md
Labels: documentation

#228 Update UG FAQ
  docs/UserGuide.md
Labels: documentation

#233 DG update
  docs/DeveloperGuide.md
Labels: documentation

#231 Fix some cosmetic bugs in DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: bug, documentation

#229 Update UG
  docs/UserGuide.md
Labels: documentation

#234 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/FindSequenceDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#232 Add some corrections and formatting
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/setWeakAfter.png
Labels: documentation

#237 Add library used
  docs/DeveloperGuide.md
  docs/index.md
Labels: documentation
