Repository AY2324S2-CS2103T-T09-1/tp, pull requests merged in 2024-03, with the labels that each got.

#43 Update NFR section in DG
  docs/DeveloperGuide.md
Labels: documentation

#44 Remove traces of AB3 in UserGuide
  docs/UserGuide.md
Labels: documentation

#48 Add grade param
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#49 Add studentId param
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/StudentId.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/StudentIdTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#50 Modify tag to create group parameter
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/StudentId.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#47 Remove Address
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#51 Branch delete phone param
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#52 Remove redundant lines in fxml file
  src/main/resources/view/PersonListCard.fxml
Labels: bug

#54 Update the title in index.md
  docs/index.md
Labels: documentation

#58 Branch delete command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudentIds.java
Labels: priority.High, type.Task

#60 Modify edit command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.High, type.Task

#53 Modify BetterModelClassDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
Labels: documentation

#63 Add group command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/GroupCommandTest.java
  src/test/java/seedu/address/logic/parser/GroupCommandParserTest.java
Labels: priority.High, type.Task

#64 Create AddSequenceDiagram puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
Labels: documentation

#88 Branch email bug
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/teachstack/logic/commands/AddCommand.java
  src/main/java/seedu/teachstack/logic/commands/EditCommand.java
  src/main/java/seedu/teachstack/model/person/Person.java
  src/main/java/seedu/teachstack/model/person/UniquePersonList.java
  src/test/java/seedu/teachstack/logic/commands/EditCommandTest.java
  src/test/java/seedu/teachstack/model/person/PersonTest.java
Labels: bug

#91 How to use UG
  docs/UserGuide.md
Labels: documentation

#92 Update link in UG
  docs/UserGuide.md
Labels: bug, documentation

#85 Display students by grade in descending order
  src/main/java/seedu/teachstack/logic/commands/DeleteCommand.java
  src/main/java/seedu/teachstack/logic/commands/EditCommand.java
  src/main/java/seedu/teachstack/logic/commands/ViewCommand.java
  src/main/java/seedu/teachstack/model/AddressBook.java
  src/main/java/seedu/teachstack/model/Model.java
  src/main/java/seedu/teachstack/model/ModelManager.java
  src/main/java/seedu/teachstack/model/person/Grade.java
  src/main/java/seedu/teachstack/model/person/Person.java
  src/main/java/seedu/teachstack/model/person/UniquePersonList.java
  src/test/java/seedu/teachstack/logic/commands/AddCommandTest.java
  src/test/java/seedu/teachstack/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/teachstack/logic/commands/EditCommandTest.java
  src/test/java/seedu/teachstack/logic/commands/FindCommandTest.java
  src/test/java/seedu/teachstack/logic/commands/GroupCommandTest.java
  src/test/java/seedu/teachstack/logic/commands/ViewCommandTest.java
  src/test/java/seedu/teachstack/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/teachstack/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/teachstack/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/teachstack/testutil/TypicalStudentIds.java
Labels: type.Task, priority.Low

#93 Add welcome message
  docs/UserGuide.md
Labels: documentation

#95 Update target audience
  docs/UserGuide.md
Labels: documentation

#96 Add Purpose of ug
  docs/UserGuide.md
Labels: documentation

#98 Add weak command
  src/main/java/seedu/teachstack/logic/commands/SetWeakThresholdCommand.java
  src/main/java/seedu/teachstack/logic/parser/AddressBookParser.java
  src/main/java/seedu/teachstack/logic/parser/SetWeakThresholdCommandParser.java
  src/main/java/seedu/teachstack/model/person/Grade.java
  src/test/java/seedu/teachstack/logic/commands/SetWeakThresholdCommandTest.java
  src/test/java/seedu/teachstack/logic/parser/SetWeakThresholdCommandParserTest.java
Labels: priority.Medium

#100 Delete command implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DeleteState1.puml
  docs/diagrams/DeleteState2.puml
  docs/diagrams/DeleteState3.puml
  docs/images/DeleteActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteState1.png
  docs/images/DeleteState2.png
  docs/images/DeleteState3.png
Labels: documentation

#97 Multiple groups
  src/main/java/seedu/teachstack/logic/commands/GroupCommand.java
  src/main/java/seedu/teachstack/logic/parser/GroupCommandParser.java
  src/main/java/seedu/teachstack/model/util/SampleDataUtil.java
  src/test/java/seedu/teachstack/logic/commands/GroupCommandTest.java
  src/test/java/seedu/teachstack/testutil/PersonBuilder.java
Labels: type.Task, priority.Medium

#102 Update the DG for add feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/AddState1.puml
  docs/diagrams/AddState2.puml
  docs/images/AddState1.png
  docs/images/AddState2.png
Labels: documentation

#107 Add diagrams and dg feature for set weak
  docs/DeveloperGuide.md
  docs/diagrams/SetWeak1.puml
  docs/diagrams/SetWeak2.puml
  docs/diagrams/SetWeakActivityDiagram.puml
  docs/images/SetWeak1.png
  docs/images/SetWeak2.png
  docs/images/SetWeakActivityDiagram.png
Labels: documentation

#105 Update the AddState diagrams
  docs/diagrams/AddState1.puml
  docs/diagrams/AddState2.puml
  docs/images/AddState1.png
  docs/images/AddState2.png
Labels: documentation

#108 Add diagrams and implementation details for find
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/FindState1.puml
  docs/diagrams/FindState2.puml
  docs/images/FindSequenceDiagram.png
  docs/images/FindState1.png
  docs/images/FindState2.png
Labels: documentation

#94 Add group command to developer guide [CS2103]
  docs/DeveloperGuide.md
  docs/diagrams/GroupState1.puml
  docs/diagrams/GroupState2.puml
  docs/diagrams/GroupState3.puml
  docs/images/GroupState1.png
  docs/images/GroupState2.png
  docs/images/GroupState3.png
Labels: documentation

#103 Update find command to filter by groups
  src/main/java/seedu/teachstack/logic/commands/FindCommand.java
  src/main/java/seedu/teachstack/logic/parser/FindCommandParser.java
  src/main/java/seedu/teachstack/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/teachstack/model/person/PersonInGroupPredicate.java
  src/test/java/seedu/teachstack/logic/commands/CommandTestUtil.java
  src/test/java/seedu/teachstack/logic/commands/FindCommandTest.java
  src/test/java/seedu/teachstack/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/teachstack/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/teachstack/model/ModelManagerTest.java
  src/test/java/seedu/teachstack/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/teachstack/model/person/PersonInGroupPredicateTest.java
Labels: priority.High, type.Task
